modLoader="javafml"
loaderVersion="[32,)"
license="ARR"
#issueTrackerURL=""
[[mods]]
modId="speedrunners"
version="{$file.jarVersion}"
displayName="Speedrunners"
authors="Jackson, bageldotjpg"
#updateJSONURL=""
#displayURL=""
#logoFile=""
description='''
A recreation of Dream's Minecraft Man Hunt/Assassin using MinecraftForge
'''

[[dependencies.speedrunners]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.64,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.speedrunners]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"